---
- name: Ensure reflector is installed
  community.general.pacman:
    name: reflector
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Configure pacman mirrors with reflector
  ansible.builtin.command:
    cmd: reflector --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
  changed_when: false
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Install essential system packages
  community.general.pacman:
    name:
      - base-devel
      - btrfs-progs
      - curl
      - efibootmgr
      - git
      - htop
      - linux-headers
      - neovim
      - networkmanager
      - openssh
      - sudo
      - util-linux
      - wget
      - yadm
      - zsh
    state: present
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Enable NetworkManager service
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: true
    state: started
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Enable SSH service
  ansible.builtin.systemd:
    name: sshd.service
    enabled: true
    state: started
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Enable Periodic TRIM for SSDs
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: true
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Install Virtual Machine Guest Agents
  community.general.pacman:
    name:
      - qemu-guest-agent
      - spice-vdagent
    state: present
  when: ansible_facts['distribution'] == 'Archlinux' and ansible_facts['virtualization_role'] == 'guest'

- name: Enable Virtual Machine Guest Agent services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - qemu-guest-agent.service
    - spice-vdagentd.socket
  failed_when: false
  when: ansible_facts['distribution'] == 'Archlinux' and ansible_facts['virtualization_role'] == 'guest'

- name: Ensure target user exists
  ansible.builtin.user:
    name: "{{ username | default('kevin') }}"
    shell: /usr/bin/zsh
    create_home: true
    groups: wheel
    append: true
    state: present

- name: Ensure wheel group has sudo access
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel ALL=\(ALL:ALL\) ALL'
    line: '%wheel ALL=(ALL:ALL) ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Check if yay is installed
  ansible.builtin.command: command -v yay
  register: system_setup_yay_check
  failed_when: false
  changed_when: false
  when: ansible_facts['distribution'] == 'Archlinux'

- name: Clone yay-bin repository # noqa: latest[git]
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay-bin.git
    version: HEAD
    dest: /tmp/yay-bin
  become: true
  become_user: "{{ username | default('kevin') }}"
  when: ansible_facts['distribution'] == 'Archlinux' and system_setup_yay_check.rc != 0

- name: Build yay
  ansible.builtin.command: makepkg --cleanbuild --nodeps --force
  changed_when: true
  args:
    chdir: /tmp/yay-bin
  become: true
  become_user: "{{ username | default('kevin') }}"
  when: ansible_facts['distribution'] == 'Archlinux' and system_setup_yay_check.rc != 0

- name: Install yay package
  ansible.builtin.shell: pacman -U --noconfirm *.pkg.tar.zst
  changed_when: true
  args:
    chdir: /tmp/yay-bin
  become: true
  when: ansible_facts['distribution'] == 'Archlinux' and system_setup_yay_check.rc != 0

- name: Ensure target user's github directory exists
  ansible.builtin.file:
    path: "/home/{{ username | default('kevin') }}/github.com/kevinjpickard"
    state: directory
    owner: "{{ username | default('kevin') }}"
    group: "{{ username | default('kevin') }}"
    mode: '0755'

- name: Clone sysconfig repository to the target filesystem
  ansible.builtin.git:
    repo: "https://github.com/kevinjpickard/sysconfig.git"
    version: main
    dest: "/home/{{ username | default('kevin') }}/github.com/kevinjpickard/sysconfig"
    update: true
  become: true
  become_user: "{{ username | default('kevin') }}"
