packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    qemu = {
      source  = "github.com/hashicorp/qemu"
      version = "~> 1"
    }
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = "~> 1"
    }
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
    vmware = {
      source  = "github.com/hashicorp/vmware"
      version = "~> 1"
    }
  }
}

variable "country" {
  type    = string
  default = "US"
}

variable "headless" {
  type    = string
  default = "false"
}

variable "iso_checksum_type" {
  type    = string
  default = "sha1"
}

variable "iso_checksum_url" {
  type    = string
  default = "https://mirrors.ocf.berkeley.edu/archlinux/iso/2020.03.01/sha1sums.txt"
}

variable "iso_url" {
  type    = string
  default = "https://mirrors.ocf.berkeley.edu/archlinux/iso/2020.03.01/archlinux-2020.03.01-x86_64.iso"
}

variable "ssh_timeout" {
  type    = string
  default = "20m"
}

source "parallels-iso" "autogenerated_1" {
  boot_command           = ["<enter><wait10><wait10><wait10><wait10>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/enable-ssh.sh<enter><wait5>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/poweroff.timer<enter><wait5>", "/usr/bin/bash ./enable-ssh.sh<enter>"]
  boot_wait              = "5s"
  disk_size              = 60480
  guest_os_type          = "linux-2.6"
  http_directory         = "srv"
  iso_checksum_type      = "${var.iso_checksum_type}"
  iso_checksum_url       = "${var.iso_checksum_url}"
  iso_url                = "${var.iso_url}"
  parallels_tools_flavor = "lin"
  parallels_tools_mode   = "attach"
  shutdown_command       = "sudo shutdown -P 0"
  ssh_password           = "vagrant"
  ssh_timeout            = "${var.ssh_timeout}"
  ssh_username           = "vagrant"
  version                = "16"
}

source "qemu" "autogenerated_2" {
  boot_command      = ["<enter><wait10><wait10><wait10><wait10>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/enable-ssh.sh<enter><wait5>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/poweroff.timer<enter><wait5>", "/usr/bin/bash ./enable-ssh.sh<enter>"]
  boot_wait         = "5s"
  disk_size         = 60480
  headless          = "${var.headless}"
  http_directory    = "srv"
  iso_checksum_type = "${var.iso_checksum_type}"
  iso_checksum_url  = "${var.iso_checksum_url}"
  iso_url           = "${var.iso_url}"
  shutdown_command  = "sudo shutdown -P 0"
  ssh_password      = "vagrant"
  ssh_timeout       = "${var.ssh_timeout}"
  ssh_username      = "vagrant"
}

source "virtualbox-iso" "autogenerated_3" {
  boot_command         = ["<enter><wait10><wait10><wait10><wait10>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/enable-ssh.sh<enter><wait5>", "/usr/bin/bash ./enable-ssh.sh<enter>"]
  boot_wait            = "5s"
  disk_size            = 60480
  guest_additions_mode = "disable"
  guest_os_type        = "ArchLinux_64"
  hard_drive_interface = "sata"
  headless             = "${var.headless}"
  http_directory       = "srv"
  iso_checksum_type    = "${var.iso_checksum_type}"
  iso_checksum_url     = "${var.iso_checksum_url}"
  iso_interface        = "sata"
  iso_url              = "${var.iso_url}"
  shutdown_command     = "sudo shutdown -P 0"
  ssh_password         = "vagrant"
  ssh_timeout          = "${var.ssh_timeout}"
  ssh_username         = "vagrant"
  vboxmanage           = [["modifyvm", "{{ .Name }}", "--firmware", "efi"]]
}

source "vmware-iso" "autogenerated_4" {
  boot_command       = ["<enter><wait10><wait10><wait10><wait10><wait10>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/enable-ssh.sh<enter><wait5>", "/usr/bin/curl -O http://{{ .HTTPIP }}:{{ .HTTPPort }}/poweroff.timer<enter><wait5>", "/usr/bin/bash ./enable-ssh.sh<enter>"]
  boot_wait          = "5s"
  cdrom_adapter_type = "sata"
  disk_size          = 64576
  guest_os_type      = "other4xlinux-64"
  headless           = "${var.headless}"
  http_directory     = "srv"
  iso_checksum_type  = "${var.iso_checksum_type}"
  iso_checksum_url   = "${var.iso_checksum_url}"
  iso_url            = "${var.iso_url}"
  memory             = 2048
  shutdown_command   = "sudo shutdown -P 0"
  ssh_password       = "vagrant"
  ssh_timeout        = "${var.ssh_timeout}"
  ssh_username       = "vagrant"
  version            = 16
  vmx_template_path  = "./archlinux_vmx_template.vmx"
}

build {
  sources = ["source.parallels-iso.autogenerated_1", "source.qemu.autogenerated_2", "source.virtualbox-iso.autogenerated_3", "source.vmware-iso.autogenerated_4"]

  provisioner "shell" {
    execute_command = "sudo sh -c '{{ .Vars }} {{ .Path }}'"
    script          = "./bootstrap_iso.sh"
  }

  provisioner "ansible-local" {
    extra_arguments = ["--connection chroot -i /mnt, --extra-vars 'chroot_exe=arch-chroot chroot_executable=/bin/bash username=kevin password=test'"]
    playbook_dir    = "./ansible"
    playbook_file   = "./ansible/setup.yml"
  }

  provisioner "shell" {
    inline = ["umount -R /mnt"]
  }

  post-processor "vagrant" {
  }
}
