---
# tasks file for applications
- debug: msg="Running on Windows"
  when: ansible_facts['kernel'] is search('Microsoft')

- debug: msg="Detected OS as {{ ansible_facts['distribution'] }}"

- name: Run OS Family Tasks
  include: "./roles/applications/tasks/{{ ansible_facts['system'] }}.yml"

- name: Run OS Specific Tasks
  include: "./roles/applications/tasks/{{ ansible_facts['distribution'] }}.yml"
