---
# Ongoing System Configuration Sync

- name: System Configuration Sync
  hosts: localhost
  connection: local
  become: true
  become_method: ansible.builtin.sudo
  gather_facts: true

  roles:
    - system_setup
    - plasma_desktop
