---
- name: Install KDE Plasma and base applications
  pacman:
    name:
      - plasma-meta
      - konsole
      - dolphin
      - sddm
      - firefox
      - vim
      - git
      - wget
    state: present

- name: Enable SDDM (Display Manager)
  systemd:
    name: sddm
    enabled: yes

- name: Enable NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes